---
abstract: 'Assorted utilities for vector-valued PDLs'
author:
  - 'Bryan Jurish'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  PDL: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: PDL-VectorValued
no_index:
  directory:
    - t
    - inc
requires:
  PDL: '0'
  Test::More: '0'
version: v1.0.5
